### PR TITLE
Add Drone Script For Docker Builds

### PR DESCRIPTION
**Pull request by zicklag**
Not tested yet. I'll finish soon.

### CODE REVIEW

**Comment by zicklag** [comment]
The build should be working correctly, but the Dockerfile apparently needs an update because it [doesn't build](https://cloud.drone.io/katharostech/roughenough/8/1/2). :)

**Comment by int08h** [comment]
@zicklag I'm taking a look at the broken build issue.

**Comment by int08h** [comment]
@zicklag Please re-attempt the Docker build. 
* I updated the Dockerfile to latest Roughenough release in #23 
* Fixed Travis times-outs in #24 

I think you're good-to-go now.

**Comment by zicklag** [comment]
It still failed: https://cloud.drone.io/katharostech/roughenough/9/1/2

It seems that there isn't a `roughenough.cfg` file in the root of the repo like the Dockerfile expects there to be. Also there isn't a `creds.json` file. Did those used to be files in the repo at one point?

**Comment by int08h** [comment]
Yup, good point. 🤦‍♂ 

Let me clean that up.

**Pull request merged**
